name: Build and Deploy

on:
  push:
    branches:
      - main
      - master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.0'
          bundler-cache: true

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Install & Build site
        run: |
          bundle install
          bundle exec jekyll build -d _site
        env:
          JEKYLL_ENV: production

      - name: Test site
        run: |
          bundle exec htmlproofer _site \
            --disable-external \
            --ignore-urls "/^http:\/\/127.0.0.1/,/^http:\/\/0.0.0.0/,/^http:\/\/localhost/"

      - name: Upload site artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages     # 바로 아래 'deploy' job과 똑같이 써야 함
          path: _site

  deploy:
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          # ↑ build job에서 설정한 name: github-pages 와 동일해야 함
          artifact_name: github-pages
