name: Build and Deploy

on:
  push:
    branches:
      - main
      - master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.0'
          bundler-cache: true

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Build site
        run: |
          bundle install
          bundle exec jekyll build -d _site
        env:
          JEKYLL_ENV: production

      # htmlproofer 실행 시, "--disable-external"을 먼저 적고 _site를 뒤에 쓰면 해결되는 경우가 많습니다
      - name: Test site
        run: bundle exec htmlproofer --disable-external _site

      - name: Upload site artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages

  deploy:
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          artifact_name: github-pages
